import { ItemStatus, ItemType } from "@/lib/constants";

type DemoItem = {
  id: number;
  title: string;
  type: ItemType;
  status: ItemStatus;
  rating: number | null;
  posterUrl: string | null;
  synopsis: string;
  releaseYear: number | null;
  runtimeMinutes: number | null;
  tags?: string | null;
  genres?: string | null;
  studios?: string | null;
  cast?: string | null;
  notes?: string | null;
  createdAt: Date;
  userId: string;
};

export const DEMO_ITEMS: DemoItem[] = [
  {
    id: 1,
    title: "Dune: Part Two",
    type: "movie",
    status: "completed",
    rating: 9.4,
    posterUrl: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    synopsis: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    releaseYear: 2024,
    runtimeMinutes: 166,
    tags: "epic,desert",
    genres: "sci-fi,adventure",
    studios: "Legendary Pictures",
    cast: "Timothee Chalamet, Zendaya",
    notes: "Best theater experience in years.",
    createdAt: new Date("2024-03-12"),
    userId: "demo",
  },
  {
    id: 2,
    title: "Oppenheimer",
    type: "movie",
    status: "completed",
    rating: 9.0,
    posterUrl: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    synopsis: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb.",
    releaseYear: 2023,
    runtimeMinutes: 180,
    tags: "biography,imax",
    genres: "drama,history",
    studios: "Universal Pictures",
    cast: "Cillian Murphy, Emily Blunt",
    notes: "Intense and unforgettable.",
    createdAt: new Date("2024-01-20"),
    userId: "demo",
  },
  {
    id: 3,
    title: "Barbie",
    type: "movie",
    status: "completed",
    rating: 8.1,
    posterUrl: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    synopsis: "Barbie suffers a crisis and journeys to the real world to find her true purpose.",
    releaseYear: 2023,
    runtimeMinutes: 114,
    tags: "satire,feel-good",
    genres: "comedy,fantasy",
    studios: "Warner Bros.",
    cast: "Margot Robbie, Ryan Gosling",
    notes: "A blast start to finish.",
    createdAt: new Date("2023-12-18"),
    userId: "demo",
  },
  {
    id: 4,
    title: "Spider-Man: No Way Home",
    type: "movie",
    status: "completed",
    rating: 8.7,
    posterUrl: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    synopsis: "Peter Parker's identity is revealed, bringing his superhero responsibilities into conflict with his normal life.",
    releaseYear: 2021,
    runtimeMinutes: 148,
    tags: "multiverse,hero",
    genres: "action,adventure",
    studios: "Marvel Studios",
    cast: "Tom Holland, Zendaya",
    notes: "Pure fan service in the best way.",
    createdAt: new Date("2023-11-06"),
    userId: "demo",
  },
  {
    id: 5,
    title: "Avatar: The Way of Water",
    type: "movie",
    status: "completed",
    rating: 8.0,
    posterUrl: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    synopsis: "Jake Sully and Neytiri's family face new threats as they explore the oceans of Pandora.",
    releaseYear: 2022,
    runtimeMinutes: 192,
    tags: "epic,underwater",
    genres: "sci-fi,adventure",
    studios: "20th Century Studios",
    cast: "Sam Worthington, Zoe Saldana",
    notes: "Visuals are insane.",
    createdAt: new Date("2023-10-02"),
    userId: "demo",
  },
  {
    id: 6,
    title: "The Last of Us",
    type: "tv",
    status: "completed",
    rating: 9.2,
    posterUrl: "https://image.tmdb.org/t/p/w500/dmo6TYuuJgaYinXBPjrgG9mB5od.jpg",
    synopsis: "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl.",
    releaseYear: 2023,
    runtimeMinutes: 60,
    tags: "post-apocalyptic,emotional",
    genres: "drama,thriller",
    studios: "HBO",
    cast: "Pedro Pascal, Bella Ramsey",
    notes: "Episode 3 wrecked me.",
    createdAt: new Date("2024-02-10"),
    userId: "demo",
  },
  {
    id: 7,
    title: "Stranger Things",
    type: "tv",
    status: "watching",
    rating: 8.8,
    posterUrl: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    synopsis: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments and supernatural forces.",
    releaseYear: 2016,
    runtimeMinutes: 55,
    tags: "80s,supernatural",
    genres: "sci-fi,thriller",
    studios: "Netflix",
    cast: "Millie Bobby Brown, Finn Wolfhard",
    notes: "Rewatching before the final season.",
    createdAt: new Date("2024-05-14"),
    userId: "demo",
  },
  {
    id: 8,
    title: "Wednesday",
    type: "tv",
    status: "completed",
    rating: 8.1,
    posterUrl: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    synopsis: "Wednesday Addams navigates her new school and a supernatural mystery.",
    releaseYear: 2022,
    runtimeMinutes: 50,
    tags: "gothic,school",
    genres: "comedy,mystery",
    studios: "Netflix",
    cast: "Jenna Ortega, Gwendoline Christie",
    notes: "The dance scene is iconic.",
    createdAt: new Date("2024-01-05"),
    userId: "demo",
  },
  {
    id: 9,
    title: "The Mandalorian",
    type: "tv",
    status: "watching",
    rating: 8.4,
    posterUrl: "https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
    synopsis: "A lone bounty hunter makes his way through the outer reaches of the galaxy.",
    releaseYear: 2019,
    runtimeMinutes: 45,
    tags: "star-wars,space",
    genres: "action,adventure",
    studios: "Lucasfilm",
    cast: "Pedro Pascal, Katee Sackhoff",
    notes: "Grogu forever.",
    createdAt: new Date("2024-04-03"),
    userId: "demo",
  },
  {
    id: 10,
    title: "Squid Game",
    type: "tv",
    status: "completed",
    rating: 8.6,
    posterUrl: "https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    synopsis: "Hundreds of cash-strapped contestants accept an invitation to compete in children's games with deadly stakes.",
    releaseYear: 2021,
    runtimeMinutes: 55,
    tags: "survival,thriller",
    genres: "drama,thriller",
    studios: "Netflix",
    cast: "Lee Jung-jae, Park Hae-soo",
    notes: "Binged in a weekend.",
    createdAt: new Date("2023-12-02"),
    userId: "demo",
  },
  {
    id: 11,
    title: "Jujutsu Kaisen",
    type: "anime",
    status: "watching",
    rating: 9.1,
    posterUrl: null,
    synopsis: "A boy swallows a cursed talisman and becomes host to a powerful curse.",
    releaseYear: 2020,
    runtimeMinutes: 24,
    tags: "curses,shonen",
    genres: "action,fantasy",
    studios: "MAPPA",
    cast: "Junya Enoki, Yuichi Nakamura",
    notes: "Season 2 was wild.",
    createdAt: new Date("2024-06-22"),
    userId: "demo",
  },
  {
    id: 12,
    title: "Demon Slayer",
    type: "anime",
    status: "completed",
    rating: 8.9,
    posterUrl: null,
    synopsis: "A boy becomes a demon slayer after his family is slaughtered and his sister is turned into a demon.",
    releaseYear: 2019,
    runtimeMinutes: 24,
    tags: "demons,action",
    genres: "action,adventure",
    studios: "ufotable",
    cast: "Natsuki Hanae, Akari Kito",
    notes: "Animation is top tier.",
    createdAt: new Date("2024-02-28"),
    userId: "demo",
  },
  {
    id: 13,
    title: "Attack on Titan",
    type: "anime",
    status: "completed",
    rating: 9.3,
    posterUrl: null,
    synopsis: "Humans fight for survival against gigantic humanoid Titans.",
    releaseYear: 2013,
    runtimeMinutes: 24,
    tags: "dark,epic",
    genres: "action,drama",
    studios: "Wit Studio",
    cast: "Yuki Kaji, Marina Inoue",
    notes: "Final season was intense.",
    createdAt: new Date("2024-03-18"),
    userId: "demo",
  },
  {
    id: 14,
    title: "Spy x Family",
    type: "anime",
    status: "watching",
    rating: 8.5,
    posterUrl: null,
    synopsis: "A spy forms a fake family to complete a mission, unaware his wife is an assassin and his daughter is a telepath.",
    releaseYear: 2022,
    runtimeMinutes: 24,
    tags: "comedy,found-family",
    genres: "comedy,action",
    studios: "Wit Studio",
    cast: "Takuya Eguchi, Atsumi Tanezaki",
    notes: "Anya steals every scene.",
    createdAt: new Date("2024-07-01"),
    userId: "demo",
  },
  {
    id: 15,
    title: "Chainsaw Man",
    type: "anime",
    status: "completed",
    rating: 8.6,
    posterUrl: null,
    synopsis: "A poor young man merges with his pet devil and becomes Chainsaw Man to survive.",
    releaseYear: 2022,
    runtimeMinutes: 24,
    tags: "dark,devils",
    genres: "action,horror",
    studios: "MAPPA",
    cast: "Kikunosuke Toya, Tomori Kusunoki",
    notes: "Wild tone swings, in a good way.",
    createdAt: new Date("2024-01-25"),
    userId: "demo",
  },
  {
    id: 16,
    title: "Baldur's Gate 3",
    type: "game",
    status: "playing",
    rating: 9.6,
    posterUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co670h.jpg",
    synopsis: "Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal.",
    releaseYear: 2023,
    runtimeMinutes: null,
    tags: "rpg,dnd",
    genres: "role-playing",
    studios: "Larian Studios",
    cast: "",
    notes: "So many choices, so little time.",
    createdAt: new Date("2024-05-03"),
    userId: "demo",
  },
  {
    id: 17,
    title: "The Legend of Zelda: Tears of the Kingdom",
    type: "game",
    status: "completed",
    rating: 9.4,
    posterUrl: null,
    synopsis: "Link explores the skies and depths of Hyrule to stop a new threat.",
    releaseYear: 2023,
    runtimeMinutes: null,
    tags: "open-world,adventure",
    genres: "adventure",
    studios: "Nintendo",
    cast: "",
    notes: "Endlessly inventive.",
    createdAt: new Date("2024-04-21"),
    userId: "demo",
  },
  {
    id: 18,
    title: "Elden Ring",
    type: "game",
    status: "completed",
    rating: 9.3,
    posterUrl: null,
    synopsis: "An open-world action RPG in the Lands Between.",
    releaseYear: 2022,
    runtimeMinutes: null,
    tags: "souls,open-world",
    genres: "action,rpg",
    studios: "FromSoftware",
    cast: "",
    notes: "Still discovering hidden areas.",
    createdAt: new Date("2024-02-07"),
    userId: "demo",
  },
  {
    id: 19,
    title: "Marvel's Spider-Man 2",
    type: "game",
    status: "playing",
    rating: 8.9,
    posterUrl: null,
    synopsis: "Peter Parker and Miles Morales face new threats as they protect New York City.",
    releaseYear: 2023,
    runtimeMinutes: null,
    tags: "superhero,open-world",
    genres: "action,adventure",
    studios: "Insomniac Games",
    cast: "",
    notes: "Traversal feels so good.",
    createdAt: new Date("2024-06-05"),
    userId: "demo",
  },
  {
    id: 20,
    title: "God of War Ragnarok",
    type: "game",
    status: "completed",
    rating: 9.1,
    posterUrl: null,
    synopsis: "Kratos and Atreus journey through the Nine Realms as Ragnarok approaches.",
    releaseYear: 2022,
    runtimeMinutes: null,
    tags: "mythology,story-rich",
    genres: "action,adventure",
    studios: "Santa Monica Studio",
    cast: "",
    notes: "Incredible character work.",
    createdAt: new Date("2024-03-30"),
    userId: "demo",
  },
];
